name: Build and Push Image in Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Install Dependencies and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.20.3
      uses: actions/setup-node@v4
      with:
        node-version: 18.20.3

    - name: Run Commands
      run: |
        npm install
        npm run build --prod
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/binary-app .

    - name: Push Image to Docker Hub
      run: docker push ${{secrets.DOCKER_USERNAME}}/binary-app
    
    - name: Connecting and Deploying to the SSH Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_SECRET_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /
          cd /docker/binary-app
          docker rm -f binary-app
          docker rmi a4sufpb/binary-app
          docker compose up -d